//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MaidRobotSystemInterfaces
{
    [Serializable]
    public class MrsEyeMsg : Message
    {
        public const string k_RosMessageName = "maid_robot_system_interfaces/MrsEye";
        public override string RosMessageName => k_RosMessageName;

        //  MaSiRo Project.
        //      Date : 2023/10/01
        // ###################################################
        public const int EMOTION_NORMAL = 0;
        public const int EMOTION_CLOSE = 1;
        public const int EMOTION_SMILE = 2;
        public const int EMOTION_CLOSE_LEFT = 3;
        public const int EMOTION_CLOSE_RIGHT = 4;
        public const int EMOTION_WINK_LEFT = 5;
        public const int EMOTION_WINK_RIGHT = 6;
        public const int EMOTION_MIENS_KEEP_NORMAL = 7;
        public const int EFFECT_CORNEA_NORMAL = 0;
        public const int EFFECT_CORNEA_ORDER = 1;
        public int emotions;
        public int cornea_effect;
        public float dimensions;
        public float distance;
        public float left_y;
        public float left_z;
        public float right_y;
        public float right_z;

        public MrsEyeMsg()
        {
            this.emotions = 0;
            this.cornea_effect = 0;
            this.dimensions = 0.0f;
            this.distance = 0.0f;
            this.left_y = 0.0f;
            this.left_z = 0.0f;
            this.right_y = 0.0f;
            this.right_z = 0.0f;
        }

        public MrsEyeMsg(int emotions, int cornea_effect, float dimensions, float distance, float left_y, float left_z, float right_y, float right_z)
        {
            this.emotions = emotions;
            this.cornea_effect = cornea_effect;
            this.dimensions = dimensions;
            this.distance = distance;
            this.left_y = left_y;
            this.left_z = left_z;
            this.right_y = right_y;
            this.right_z = right_z;
        }

        public static MrsEyeMsg Deserialize(MessageDeserializer deserializer) => new MrsEyeMsg(deserializer);

        private MrsEyeMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.emotions);
            deserializer.Read(out this.cornea_effect);
            deserializer.Read(out this.dimensions);
            deserializer.Read(out this.distance);
            deserializer.Read(out this.left_y);
            deserializer.Read(out this.left_z);
            deserializer.Read(out this.right_y);
            deserializer.Read(out this.right_z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.emotions);
            serializer.Write(this.cornea_effect);
            serializer.Write(this.dimensions);
            serializer.Write(this.distance);
            serializer.Write(this.left_y);
            serializer.Write(this.left_z);
            serializer.Write(this.right_y);
            serializer.Write(this.right_z);
        }

        public override string ToString()
        {
            return "MrsEyeMsg: " +
            "\nemotions: " + emotions.ToString() +
            "\ncornea_effect: " + cornea_effect.ToString() +
            "\ndimensions: " + dimensions.ToString() +
            "\ndistance: " + distance.ToString() +
            "\nleft_y: " + left_y.ToString() +
            "\nleft_z: " + left_z.ToString() +
            "\nright_y: " + right_y.ToString() +
            "\nright_z: " + right_z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
