//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MaidRobotSystemInterfaces
{
    [Serializable]
    public class MrsHeadStatusMsg : Message
    {
        public const string k_RosMessageName = "maid_robot_system_interfaces/MrsHeadStatus";
        public override string RosMessageName => k_RosMessageName;

        //  MaSiRo Project.
        //      Date : 2023/12/24
        // ###################################################
        public bool human_detected;

        public MrsHeadStatusMsg()
        {
            this.human_detected = false;
        }

        public MrsHeadStatusMsg(bool human_detected)
        {
            this.human_detected = human_detected;
        }

        public static MrsHeadStatusMsg Deserialize(MessageDeserializer deserializer) => new MrsHeadStatusMsg(deserializer);

        private MrsHeadStatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.human_detected);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.human_detected);
        }

        public override string ToString()
        {
            return "MrsHeadStatusMsg: " +
            "\nhuman_detected: " + human_detected.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
