//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MaidRobotSystemInterfaces
{
    [Serializable]
    public class MrsLipMsg : Message
    {
        public const string k_RosMessageName = "maid_robot_system_interfaces/MrsLip";
        public override string RosMessageName => k_RosMessageName;

        //  MaSiRo Project.
        //      Date : 2023/10/01
        // ###################################################
        public int percent;

        public MrsLipMsg()
        {
            this.percent = 0;
        }

        public MrsLipMsg(int percent)
        {
            this.percent = percent;
        }

        public static MrsLipMsg Deserialize(MessageDeserializer deserializer) => new MrsLipMsg(deserializer);

        private MrsLipMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.percent);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.percent);
        }

        public override string ToString()
        {
            return "MrsLipMsg: " +
            "\npercent: " + percent.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
