//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MaidRobotSystemInterfaces
{
    [Serializable]
    public class MrsNeckMsg : Message
    {
        public const string k_RosMessageName = "maid_robot_system_interfaces/MrsNeck";
        public override string RosMessageName => k_RosMessageName;

        //  MaSiRo Project.
        //      Date : 2023/10/01
        // ###################################################
        public float x;
        public float y;
        public float z;
        public float w;

        public MrsNeckMsg()
        {
            this.x = 0.0f;
            this.y = 0.0f;
            this.z = 0.0f;
            this.w = 0.0f;
        }

        public MrsNeckMsg(float x, float y, float z, float w)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.w = w;
        }

        public static MrsNeckMsg Deserialize(MessageDeserializer deserializer) => new MrsNeckMsg(deserializer);

        private MrsNeckMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
            deserializer.Read(out this.w);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.Write(this.w);
        }

        public override string ToString()
        {
            return "MrsNeckMsg: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\nw: " + w.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
